### ISSUE TITLE
Statsd library has updated, broke BC.

### ISSUE THREAD

**Issue by eeroniemi** [stevencorona/opcache-json#3]
When I tried to run the example code on README.md (or example.php) I got this error:

```
PHP Fatal error:  Class 'Domnikl\Statsd\Connection\Socket' not found in /opt/opcache-json/send_to_statsd.php on line 6
```

Reason is that domnikl/statsd-php 1.0 to 2.0 update has broken BC.

I fixed this, PR coming.

**Comment by eeroniemi** [comment]
@stevencorona ping, could you merge this? without this this whole library won't work. in the meantime if someone wants to actually use this library, feel free to use https://github.com/eeroniemi/opcache-json master branch

**Comment by stevencorona** [comment]
Thanks! I'll look at this today.
